export default {
  action1: '创建',
  action2: '更新',
  action3: '删除',
  action4: '发布',
  time: '时间范围',
  image: '图片',
  content: '内容',
  color: '文字颜色',
  backgroundColor: '背景色',
  backgroundImage: '背景图片',
  textAlign: '对齐方式',
  padding: '内边距',
  margin: '外边距',
  height: '高度',
  link: '链接',
  shareTitle: '分享标题',
  shareLink: '分享链接',
  shareContent: '分享内容',
  wheel: ['上','右','下','左'],
  font: '文字样式'
}
